### PR TITLE
Add METER, NOTIFICATION and revise BASIC SET

### PR DESCRIPTION
**Pull request by TedTolboom**
Add METER to measure_current, _voltage
Add NOTIFICATION to alarm_motion, _contact, _tamper
BASIC_SET to BASIC_REPORT as discussed on Slack

### CODE REVIEW

**Comment by RobinBol** [comment]
I see you changed basic set to basic report, did you also read my reply on your question regarding the basic command class?

**Comment by TedTolboom** [comment]
Hi Robin, yes and also responded to it.. let's continue on Slack

**Comment by TedTolboom** [comment]
Hi Robin,

Added the ALARM_BATTERY capability to the lib

Regarding the ONOFF capability + BASIC command class

My proposal to keep it consistent, it to change the current BASIC.json to BASIC_SET.json and add the default BASIC set, get, report parsers to the BASIC.json...
Is that an option you can agree on?

**Comment by jeroenvollenbrock** [comment]
@TedTolboom 
@RobinBol is currently out of office, i see you're referring to a private slack conversation you had, which makes me a bit reluctant to merge this myself. Is it okay if i delay this PR until he is back from his holidays?

**Comment by TedTolboom** [comment]
@jeroenvollenbrock not private; in plain sight in #zwave-zigbee...

my summary:
It's a bit fundamental discussion... 
In the current way adding the command_class specifications to the capabilities; the CC commands are pretty straightforward; for SWITCH_MULTILEVEL:
```
get: 'SWITCH_MULTILEVEL_GET',
set: 'SWITCH_MULTILEVEL_SET', 
report: 'SWITCH_MULTILEVEL_REPORT',
```
ie. the get is a GET command, the set is a SET command and the report is a REPORT command... 

Which holds for all, except 1 COMMAND_CLASS: BASIC for onoff.. 
here a set command is linked to a report:
`report: 'BASIC_SET',`
Which is a known trick to use BASIC_SET commands of e.g. a multichannel node reported on a different association group as input.

It happened to be that I was integrating a device that is using the BASIC class to get, set and report... where I thought I could use the predefined BASIC onoff capability, but which was not working...

My advice (as part of this PR) is to keep the default specification consistent; a get is a GET, a set is a SET and a report is a REPORT... the meshdriver is such a good solution to keep it simple.

If in the proposed way, a developer chooses to use an alternative option (trick) let him do it explicitely (overwrite the default parsers)... 
alternative could be to use the proposed BASIC_SET option for onoff as proposed in this PR

If you like to discuss this with @RobinBol or internally first,  I'm fine with that...

**Comment by mruiter** [comment]
@RobinBol please accept the pull.

I need these basic's for the NEO app also.

**Comment by TedTolboom** [comment]
Additional debug logging for electrical capabilities (from Aeotec Smart Dimmer-6, Neo NAS-WR01ZE and Hank HKZW-SO0x):

Parsers used in SDK1 apps and original SDK2 meshdriver are inconclusive. measure_voltage and measure_power would both be mixed up since both parsers only filtered on `'Scale bits 10': 0`
Approach of NEO (using the size as discriminator) is also not something usable for multiple devices / brands.
```
AEOTEC v3
measure_power: 'Scale bit 2': false, 'Scale bits 10': 2,
meter_power: 'Scale bit 2': false, 'Scale bits 10': 0,
meter_current 'Scale bit 2': true, 'Scale bits 10': 1,
measure_voltage: 'Scale bit 2': true, 'Scale bits 10': 0
===============

NEO v4
measure_power: 'Scale bit 2': false, 'Scale bits 10': 2,
meter_power: 'Scale bit 2': false, 'Scale bits 10': 0,
measure_current: 'Scale bit 2': true, 'Scale bits 10': 1,
measure_voltage: 'Scale bit 2': true, 'Scale bits 10': 0
===============

HANK V3
measure_power: 'Scale bit 2': false, 'Scale bits 10': 2,
meter_power: 'Scale bit 2': false, 'Scale bits 10': 0,
measure_current: 'Scale bit 2': true, 'Scale bits 10': 1, 
measure_voltage: 'Scale bit 2': true, 'Scale bits 10': 0

AEOTEC v3

measure_power: 'Scale bit 2': false, 'Scale bits 10': 2,
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 74>,
     Properties2: { Size: 4, 'Scale bits 10': 2, Precision: 3 },
     'Meter Value': <Buffer 00 00 22 ad>,
     'Delta Time (Raw)': <Buffer 00 00>,
     'Delta Time': 0,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 8.877,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }

measure_voltage: 'Scale bit 2': true, 'Scale bits 10': 0
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer a1>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': true,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 03 8e 66>,
     'Delta Time (Raw)': <Buffer 00 00>,
     'Delta Time': 0,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 233.062,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }

meter_current 'Scale bit 2': true, 'Scale bits 10': 1,
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer a1>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': true,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 6c>,
     Properties2: { Size: 4, 'Scale bits 10': 1, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 4a>,
     'Delta Time (Raw)': <Buffer 00 00>,
     'Delta Time': 0,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0.074,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }

meter_power: 'Scale bit 2': false, 'Scale bits 10': 0,
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 03 12>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 03 12>,
     'Meter Value (Parsed)': 0.786,
     'Previous Meter Value (Parsed)': 0.786 },
  '2': null }

===============
NEO v4

measure_power: 'Scale bit 2': false, 'Scale bits 10': 2,
2017-08-30 20:14:50 [log] [ManagerDrivers] [NAS-WR01ZE] [2] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1':
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1:
      { 'Scale bit 2': false,
        'Meter Type': 'Electric meter',
        'Rate Type': 'Import',
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 54>,
     Properties2: { Size: 4, 'Scale bits 10': 2, Precision: 2 },
     'Meter Value': <Buffer 00 00 03 45>,
     'Delta Time (Raw)': <Buffer 01 d6>,
     'Delta Time': 470,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Scale 2 (Raw)': <Buffer 00>,
     'Scale 2': 0,
     'Meter Value (Parsed)': 8.37,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
  
meter_power: 'Scale bit 2': false, 'Scale bits 10': 0,
2017-08-30 20:14:53 [log] [ManagerDrivers] [NAS-WR01ZE] [2] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1':
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1:
      { 'Scale bit 2': false,
        'Meter Type': 'Electric meter',
        'Rate Type': 'Import',
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 44>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 2 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 04>,
     'Delta Time': 4,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Scale 2 (Raw)': <Buffer 00>,
     'Scale 2': 0,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }

measure_current: 'Scale bit 2': true, 'Scale bits 10': 1,
2017-08-30 20:14:52 [log] [ManagerDrivers] [NAS-WR01ZE] [2] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1':
   { 'Properties1 (Raw)': <Buffer a1>,
     Properties1:
      { 'Scale bit 2': true,
        'Meter Type': 'Electric meter',
        'Rate Type': 'Import',
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 4a>,
     Properties2: { Size: 2, 'Scale bits 10': 1, Precision: 2 },
     'Meter Value': <Buffer 00 6c>,
     'Delta Time (Raw)': <Buffer 01 d6>,
     'Delta Time': 470,
     'Previous Meter Value': <Buffer 00 00>,
     'Scale 2 (Raw)': <Buffer 00>,
     'Scale 2': 0,
     'Meter Value (Parsed)': 1.08,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }

measure_voltage: 'Scale bit 2': true, 'Scale bits 10': 0
2017-08-30 20:14:51 [log] [ManagerDrivers] [NAS-WR01ZE] [2] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1':
   { 'Properties1 (Raw)': <Buffer a1>,
     Properties1:
      { 'Scale bit 2': true,
        'Meter Type': 'Electric meter',
        'Rate Type': 'Import',
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 42>,
     Properties2: { Size: 2, 'Scale bits 10': 0, Precision: 2 },
     'Meter Value': <Buffer 60 28>,
     'Delta Time (Raw)': <Buffer 01 d6>,
     'Delta Time': 470,
     'Previous Meter Value': <Buffer 5f f7>,
     'Scale 2 (Raw)': <Buffer 00>,
     'Scale 2': 0,
     'Meter Value (Parsed)': 246.16,
     'Previous Meter Value (Parsed)': 245.67 },
  '2': null }
  
====== 
HANK V3

measure_power: 'Scale bit 2': false, 'Scale bits 10': 2,
2017-08-30 21:32:15 [log] [ManagerDrivers] [HKZW-SO0x] [0] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 74>,
     Properties2: { Size: 4, 'Scale bits 10': 2, Precision: 3 },
     'Meter Value': <Buffer 00 00 1e 40>,
     'Delta Time (Raw)': <Buffer 00 00>,
     'Delta Time': 0,
     'Meter Value (Parsed)': 7.744 },
  '2': null }  
  
  meter_power: 'Scale bit 2': false, 'Scale bits 10': 0,
  2017-08-30 21:56:16 [log] [ManagerDrivers] [HKZW-SO0x] [0] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 36>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 36>,
     'Meter Value (Parsed)': 0.054,
     'Previous Meter Value (Parsed)': 0.054 },
  '2': null }
  
  measure_current: 'Scale bit 2': true, 'Scale bits 10': 1, 
  2017-08-30 21:31:45 [log] [ManagerDrivers] [HKZW-SO0x] [0] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer a1>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': true,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 6c>,
     Properties2: { Size: 4, 'Scale bits 10': 1, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 00>,
     'Delta Time': 0,
     'Meter Value (Parsed)': 0 },
  '2': null }
  
measure_voltage: 'Scale bit 2': true, 'Scale bits 10': 0
  [debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer a1>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': true,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 03 8d 7d>,
     'Delta Time (Raw)': <Buffer 00 00>,
     'Delta Time': 0,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 232.829,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
```

**Pull request merged**
