### PR TITLE
Feature/report parser override

### PR DESCRIPTION
**Pull request by MatthewWaanders**

### CODE REVIEW

**Comment by WeeJeWel** [comment]
Could you add an example what the previous situation, and the new situation is? Makes it a lot easier to read the PR.

**Comment by MatthewWaanders** [comment]
Previously:

```
this.registerCapability('meter_power', 'METER', {
    reportParser: return this._doSomething(),
});
```

Wouldn't override the predefined versioned reportParsers in MeshDriver.

Now when you do the same:
```
this.registerCapability('meter_power', 'METER', {
    reportParser: return this._doSomething(),
});
```

It does override all the reportParsers available, if you don't want this you can do the following:
```
this.registerCapability('meter_power', 'METER', {
    reportParser: return this._doSomething(),
    reportParserOverride: false
});
```

**Comment by WeeJeWel** [comment]
Brilliant. (I hope you wrap the doSomething() in an anonymous function, though.)

**Comment by caseda** [comment]
Maybe make it opt-in (report Parser Overwrite needs to be true) instead of opt-out as pretty much all functions are opt-in. 
To keep it consistent, and catch accidental additions.

**Comment by MatthewWaanders** [comment]
In my opinion you won't declare a reportParser function if you don't want to override the other reportParsers, as such I've decided to make this an implicit override with an explicit opt-out in the case you do not want to do so.

Please keep in mind that declaring a versioned reportParser won't override all reportParsers. This implicit override is only for when the programmer declares a version less reportParser.

**Comment by RobinBol** [comment]
I have to agree with @caseda, I think many drivers declare a `reportParser` just as a fallback, which will catch all non-defined report versions. If this is opt-out we would have to add the flag to most of the currently implemented SDKv2 drivers. Besides, this functionality was added to catch an edge case (the need to override all possible versions of the `reportParser`), so changing the default behaviour does not seem logical to me.

**Comment by MatthewWaanders** [comment]
Swapped it around! Now you need to explicitly set `reportParserOverride` to `true`

**Pull request merged**
