### PR TITLE
added light capabilities

### PR DESCRIPTION
**Pull request by aartse**
added light capabilities for command_class SWITCH_COLOR.

i added only the setter because i don't know how to implement "get : 'SWITCH_COLOR_GET'" for mutiple calls. because SWITCH_COLOR needs 5 get calls with different "Color Component ID" to get all the color channels. Now i added the code in the device_id/driver.js file, but it is better to add this code in the light_hue/SWITCH_COLOR.js file?

### CODE REVIEW

**Comment by caseda** [comment]
I won't recommend to do this, but add it as a full starting device to expand on (like it is done now for the lock device).
That will save about 70-80% of data being send and received.
And more likely to not fail.. 

BTW, Dit you test this? 😉

**Comment by RobinBol** [comment]
Hi @aartse, thanks for your contribution! In my opinion, since color control is a rather complicated process using multiple capabilities and multiple different capability parsers, it would be better to create a separate device class for it with the custom capability parsers implemented. This was also done for ZigBee for example: https://github.com/athombv/node-homey-meshdriver/blob/master/lib/zigbee/ZigBeeLightDevice.js

**Comment by wdttilburg** [comment]
@caseda i have test this with 2 rgbw bulbs for zipato. it dit work, but after 2 day's, sometimes 1 of the bulbs does not change the color. when sending it again, the color changed.

@RobinBol, thnx for the example, i'll look into it.

**Comment by aartse** [comment]
@caseda i have test this with 2 rgbw bulbs for zipato. it dit work, but after 2 day's, sometimes 1 of the bulbs does not change the color. when sending it again, the color changed.

@RobinBol, thnx for the example, i'll look into it.

**Comment by RobinBol** [comment]
Regarding my previous comment, I'll close this PR for now since it is not the desired approach. But thanks again for your contribution!

**Pull request closed without merging**
