### PR TITLE
Feature/polling enhancements

### PR DESCRIPTION
**Pull request by MatthewWaanders**
added multiplication factor for pollIntervals, added public method for refreshing a capability once

### CODE REVIEW

**Comment by WeeJeWel** [comment]
LGTM. Please also build the new docs and include them in the PR.

**Comment by caseda** [comment]
Duplicate of #57 though this _is_ good? Thanks :joy:

**Comment by WeeJeWel** [comment]
@caseda Haha oops. Maybe @RobinBol has a different opinion about this than I do.

**Comment by caseda** [comment]
Maybe, who knows, as you are the one declining my request

**Comment by WeeJeWel** [comment]
Am I missing something? It looks like in PR #57 Robin closed it, so that is why I am waiting for his feedback on this.

**Comment by TedTolboom** [comment]
@weejewel ssssst... we all agree this is needed...

**Pull request merged**
