### PR TITLE
Fixes grouped settings not being checked in onSettings of ZwaveDevice

### LINKED ISSUE #33: Unable to set Z-wave parameters for grouped settings: manifestSetting = undefined
On latest Z-wave meshdriver (1.2.4) and Homey 1.5.3

For a device, I grouped settings per button (4 groups) for user readability.
image

All settings outside the groups are working properly, but the settings inside the groups are not.
the manifestSetting including Z-wave object remains undefined:
https://github.com/athombv/node-homey-meshdriver/blob/master/lib/zwave/ZwaveDevice.js#L53

the `manifest.settings` shows:
```
  settings: 
   [ { id: 'upper_paddle_mode',
       zwave: [Object],
       value: '0',
       type: 'dropdown',
       label: [Object],
       hint: [Object],
       values: [Array] },
     { id: 'lower_paddle_mode',
       zwave: [Object],
       value: '0',
       type: 'dropdown',
       label: [Object],
       hint: [Object],
       values: [Array] },
     { id: 'relay_mode',
       zwave: [Object],
       value: '1',
       type: 'dropdown',
       label: [Object],
       hint: [Object],
       values: [Array] },
     { id: 'indicator_mode',
       zwave: [Object],
       value: '1',
       type: 'dropdown',
       label: [Object],
       hint: [Object],
       values: [Array] },
     { id: 'scene_offset',
       zwave: [Object],
       value: 1,
       type: 'number',
       attr: [Object],
       label: [Object],
       hint: [Object] },
     { id: 'disable_house_cleaning_mode',
       zwave: [Object],
       value: false,
       type: 'checkbox',
       label: [Object],
       hint: [Object] },
     { id: 'threshold_longpress',
       zwave: [Object],
       value: 50,
       type: 'number',
       attr: [Object],
       label: [Object],
       hint: [Object] },
     { type: 'group',
       label: [Object],
       collapsed: true,
       children: [Array] },
     { type: 'group',
       label: [Object],
       collapsed: true,
       children: [Array] },
     { type: 'group',
       label: [Object],
       collapsed: true,
       children: [Array] },
     { type: 'group',
       label: [Object],
       collapsed: true,
       children: [Array] } ] 
```
Please adapt the meshdriver to also look into the children of the defined groups...

### PR DESCRIPTION
**Pull request by BasKiers**
Added function to flatten settings by unpacking setting groups and caches them

fixes #33

### CODE REVIEW

**Comment by TedTolboom** [comment]
@BasKiers this one is not working... 
Error: "Cannot read property 'find' of undefined"

The modifications made in below file, I can confirm to be working:
https://github.com/TedTolboom/dk.logichome/blob/SDK2/node_modules/homey-meshdriver/lib/zwave/ZwaveDevice.js

**Comment by BasKiers** [comment]
@TedTolboom Thanks, fixed the pull request.

**Comment by TedTolboom** [comment]
Will check the updated code this evening and provide feedback.

Ted

**Comment by RobinBol** [comment]
@TedTolboom did you already found time to check if this PR resolves your issue?

**Comment by TedTolboom** [comment]
@RobinBol confirmed to be working ok! Thanks @BasKiers

**Pull request merged**
